<[2020-03-30 20:23:11.632809] 비정상@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 20:24:14.496189] 비정상@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 20:25:29.514967] 비정상@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 20:26:43.243189] 비정상@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 20:36:12.469172] 비정상@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 21:01:35.258935] 비정상@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 21:12:33.818503] 정상@naver.com 정상처리 >
<[2020-03-30 21:19:55.388653] 정상@naver.com 정상처리 >
<[2020-03-30 21:22:53.515178] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 21:23:53.033842] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 21:59:20.501738] 정상@naver.com 정상처리 >
<[2020-03-30 21:59:41.849243] 정상@naver.com 정상처리 >
<[2020-03-30 22:02:13.151152] 정상@naver.com 정상처리 >
<[2020-03-30 22:02:32.298466] 정상@naver.com 정상처리 >
<[2020-03-30 22:02:44.954081] 정상@naver.com 정상처리 >
<[2020-03-30 22:03:07.140329] 정상@naver.com 정상처리 >
<[2020-03-30 22:03:38.920154] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 22:03:53.218645] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 22:03:55.083189] 정상@naver.com 정상처리 >
<[2020-03-30 22:04:08.639673] 정상@naver.com 정상처리 >
<[2020-03-30 22:04:11.156723] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 22:15:09.479412] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 22:15:21.498987] 정상@naver.com 정상처리 >
<[2020-03-30 22:16:04.142135] 정상@naver.com 정상처리 >
<[2020-03-30 22:20:46.704337] 정상@naver.com 정상처리 >
<[2020-03-30 22:21:47.552779] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
<[2020-03-30 22:22:07.239671] 정상@naver.com 정상처리 >
<[2020-03-30 22:23:31.631301] 정상@naver.com 정상처리 >
<[2020-03-30 22:23:46.429035] 비정상에러@naver.com 컴파일에러 Traceback(mostrecentcalllast):File"./temp/5255/data/sample_template_02.py",line80,in<module>date=pd.data('20200326',period=6)File"/home/jb/python/projects/data-election/dataVenv/lib/python3.8/site-packages/pandas/__init__.py",line263,in__getattr__raiseAttributeError(f"module'pandas'hasnoattribute'{name}'")AttributeError:module'pandas'hasnoattribute'data'>
